loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('post.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('post/', include('post.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.Feed.as_view(), name="feed"),
]

post/models.py
from django.db import models
from django.contrib.auth.models import User

class Comentario(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField()
    imagem = models.ImageField(upload_to='imagens/%Y/%m/', blank=True, null=True)
    data_resposta = models.DateTimeField(auto_now_add=True)
    reacao = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.autor} - {self.data_resposta}'

class Post(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    legenda = models.TextField()
    imagem = models.ImageField(upload_to='imagens/%Y/%m/', blank=True, null=True)
    data_postagem = models.DateTimeField(auto_now_add=True)
    comentario = models.ManyToManyField(Comentario, null=True, blank=True)
    reacao = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.autor} - {self.data_postagem}'

post/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from django.urls import reverse
from post.models import Post, Comentario

class Feed(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()  # Adjust this query based on your model and filtering needs
        return render(request, 'feed.html', {'posts': posts})

class SalvarPost(View):
    def post(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login.'
            )
            return redirect('perfil:cadastrar')

        legenda = self.request.POST.get('legenda')
        imagem = self.request.POST.get('imagem')
        data_postagem = self.request.POST.get('data_postagem')
        comentario = self.request.POST.get('comentario')
        reacao = self.request.POST.get('reacao')

        post = Post(
            autor=self.request.user,
            legenda=legenda,
            imagem=imagem,
            data_postagem=data_postagem,
            comentario=comentario,
            reacao=reacao
        )

        post.save()

        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': post.pk
                }
            )
        )

class SalvarComentario(View):
    def post(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login.'
            )
            return redirect('perfil:cadastrar')

        texto = self.request.POST.get('texto')
        imagem = self.request.POST.get('imagem')
        data_resposta = self.request.POST.get('data_resposta')
        reacao = self.request.POST.get('reacao')

        comentario = Comentario(
            autor=self.request.user,
            texto=texto,
            imagem=imagem,
            data_resposta=data_resposta,
            reacao=reacao
        )

        comentario.save()

        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': comentario.pk
                }
            )
        )

post/templates/feed.html
{% extends "base.html" %}

{% block titulo %}Feed | {% endblock %}

{% block conteudo %}
    {% for post in posts %}
        <div class="flex flex-col items-center gap-5">
            <h2 class="card-title">{{ post.autor }}</h5>
            <p class="card-text">{{ post.data_postagem }}</p>
            <p class="card-text">{{ post.legenda }}</p>
            {% if post.imagem %}
                <a href="{% url 'post:feed' %}">
                    <img class="w-96" src="{{ post.imagem.url }}" alt="{{ post.legenda }}">
                </a>
            {% endif %}
            <p class="card-text">{{ post.reacao }} reações</p>
            <div class="card-body">
                {% for comentario in post.comentario.all %}
                    <p class="card-text">{{ comentario.texto }}</p>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
{% endblock conteudo %}

post/templates/post.html
{% extends 'base.html' %}
{% block titulo %}{{ post.nome }} | {% endblock %}

{% block conteudo %}
    <div class="row">
        <div class="col-lg">
            <div class="row no-gutters">
                <div class="col-lg-12">
                    {% if post.imagem %}
                        <img class="img-fluid" src="{{ post.imagem.url }}" alt="{{ post.legenda }}">
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}