loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('post.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('post/', include('post.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Cadastrar.as_view(), name='cadastrar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name="lista"),
    path('<slug>', views.DetalheProduto.as_view(), name="detalhe"),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(), name="adicionaraocarrinho"),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name="removerdocarrinho"),
    path('carrinho/', views.Carrinho.as_view(), name="carrinho"),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name="resumodacompra"),
    path('busca/', views.Busca.as_view(), name="busca"),
]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User

class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido N. {self.pk}'

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

pedido/views.py
from django.shortcuts import redirect, reverse
from django.views.generic import ListView, DetailView
from django.views import View
from django.contrib import messages
from produto.models import Variacao
from .models import Pedido, ItemPedido
from utils import utils

class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:cadastrar')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(usuario=self.request.user)
        return qs

class Pagar(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/pagar.html'
    model = Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'

class SalvarPedido(View):
    template_name = 'pedido/pagar.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login.'
            )
            return redirect('perfil:cadastrar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Seu carrinho está vazio.'
            )
            return redirect('produto:lista')

        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [v for v in carrinho]
        bd_variacoes = list(
            Variacao.objects.select_related('produto')
            .filter(id__in=carrinho_variacao_ids)
        )

        for variacao in bd_variacoes:
            vid = str(variacao.id)

            estoque = variacao.estoque
            qtd_carrinho = carrinho[vid]['quantidade']
            preco_unt = carrinho[vid]['preco_unitario']
            preco_unt_promo = carrinho[vid]['preco_unitario_promocional']

            error_msg_estoque = ''

            if estoque < qtd_carrinho:
                carrinho[vid]['quantidade'] = estoque
                carrinho[vid]['preco_quantitativo'] = estoque * preco_unt
                carrinho[vid]['preco_quantitativo_promocional'] = estoque * \
                    preco_unt_promo

                error_msg_estoque = 'Estoque insuficiente para alguns '\
                    'produtos do seu carrinho. '\
                    'Reduzimos a quantidade desses produtos. Por favor, '\
                    'verifique quais produtos foram afetados a seguir.'

            if error_msg_estoque:
                messages.error(
                    self.request,
                    error_msg_estoque
                )

                self.request.session.save()
                return redirect('produto:carrinho')

        qtd_total_carrinho = utils.cart_total_qtd(carrinho)
        valor_total_carrinho = utils.cart_total(carrinho)

        pedido = Pedido(
            usuario=self.request.user,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )

        pedido.save()

        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        del self.request.session['carrinho']

        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': pedido.pk
                }
            )
        )

class Detalhe(DispatchLoginRequiredMixin, DetailView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'pedido/detalhe.html'
    pk_url_kwarg = 'pk'

class Lista(DispatchLoginRequiredMixin, ListView):
    model = Pedido
    context_object_name = 'pedidos'
    template_name = 'pedido/lista.html'
    paginate_by = 10
    ordering = ['-id']

templates/parciais/_carrinho.html
{% load static %}
{% load brfilters %}

<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>

        {% for linha in carrinho.values %}

            <tr>
                <td class="d-none d-lg-block">
                    <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}">
                </td>
                <td>
                    <a href="{% url 'produto:detalhe' linha.slug %}">
                        {{ linha.produto_nome }}
                    </a>

                    <a class="ml-3" href="{% url 'produto:removerdocarrinho' %}?vid={{ linha.variacao_id }}">
                        <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                    </a>
                </td>
                <td>{{ linha.variacao_nome }}</td>
                <td>
                    {{ linha.quantidade }} x
                    {% if linha.preco_unitario_promocional %}
                        {{ linha.preco_unitario_promocional }}
                    {% else %}
                        {{ linha.preco_unitario }}
                    {% endif %}
                </td>

                {% if linha.preco_quantitativo_promocional %}
                    <td>{{ linha.preco_quantitativo_promocional|formata_preco }}</td>
                {% else %}
                    <td>{{ linha.preco_quantitativo|formata_preco }}</td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
</div>

templates/parciais/_footer.html
{% load static %}

<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">Por Breno Lima & Rodrigo L. Algeri</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js'%}"></script>
<script src="{% static 'assets/custom/js/scripts.js'%}"></script>

templates/parciais/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css'%}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css'%}"> -->

<script src="https://cdn.tailwindcss.com"></script>
<script src="/../../static/assets/js/scripts.js" defer></script>
<script src="https://unpkg.com/@themesberg/flowbite@latest/dist/flowbite.bundle.js"></script>
<link rel="stylesheet" href="/static/assets/custom/css/style.css">

templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/parciais/_modal.html
<!-- Modal Conta -->
{% if not request.user.is_authenticated %}
    <dialog id="modalConta" class="open:flex modalConta rounded-2xl h-3/5 w-2/5">
        <div class="flex flex-1 modal-box">
            {% comment %} <form method="post" action="{% url 'perfil:login' %}">
                {% csrf_token %}
                <button class="focus:outline-0 btnConta btn-sm btn-circle btn-ghost absolute right-3 top-1 text-xl rounded-s-full z-20 text-slate-500">✕</button>
            </form> {% endcomment %}
            <div class="flex bg-slate-100 w-full h-full">
                <div class="flex w-2/5">
                    <div class="flex flex-col items-center gap-2">
                        <img class="h-full" src="/media/imagens/modalLoginImagem.jpg" alt="">
                    </div>
                </div>
                <main class="flex flex-1 justify-center bg-white">
                    <div class="flex items-center justify-center flex-col gap-4">
                        <div>
                            <h1 class="h1TituloLogin text-xl font-medium">Bem-vindo ao Marketplace </h1>
                            <p>Seu painel de administração</p>
                        </div>
                        <div class="flex gap-6">
                            <div class="flex border border-slate-300 py-1 px-8 rounded-md hover:bg-slate-100 transition-all duration-300 cursor-pointer">
                                <button class="flex items-center gap-4"><img src="/media/imagens/login-google.svg" alt=""></button>
                            </div>
                            <div class="flex border border-slate-300 py-1 px-8 rounded-md hover:bg-slate-100 transition-all duration-300 cursor-pointer">
                                <button class="flex items-center gap-4"><img src="/media/imagens/login-facebook.svg" alt=""></button>
                            </div>
                        </div>
                        <div>
                            <h6 id="separador"><span class="text-slate-500">ou faça login com</span></h6>
                        </div>
                        <form method="post" action="{% url 'perfil:login' %}" class="flex w-full flex-col gap-2">
                            {% csrf_token %}
                            <div class="flex flex-col flex-1 gap-6">
                                <div class="flex flex-col gap-1">
                                    <label class="text-x1" for="usuario">Nome de usuário</label>
                                    <input class="border border-slate-300 h-12 px-4 rounded-md focus:outline-blue-700 transition-all duration-300" type="text" name="username" id="usuario"
                                        placeholder="Digite seu usuário ou seu email">
                                </div>
                                <div class="flex flex-col gap-1">
                                    <label class="text-x1" for="password">Senha</label>
                                    <input class="border border-slate-300 h-12 px-4 rounded-md focus:outline-blue-700 transition-all duration-300" type="password" name="password" id="password"
                                        placeholder="Senha">
                                </div>
                            </div>
                            <div class="flex items-center justify-between">
                                <div class="flex items-center gap-1">
                                    <input id="ipCheckbox" class="accent-blue-700" type="checkbox" checked>
                                    <label class="text-sm" for="ipCheckbox">Lembre-me</label>
                                </div>
                                <a class="text-blue-700 font-medium" href="#">Esqueceu sua senha?</a>
                            </div>
                            <div class="botaoEntrar cursor-pointer flex flex-1 items-center justify-center mt-6 bg bg-blue-500 p-1 bg-gradient-to-b from-blue-500 to-blue-700 rounded-md py-2.5">
                                <button type="submit" class="text-xl font-semibold text-white">Entrar</button>
                            </div>
                            <div class="flex gap-5 mt-1">
                                <p>Novo usuário em Marketplace?</p>
                                <a class="text-blue-700 font-medium" href="{% url 'perfil:cadastrar' %}">Crie sua conta</a>
                            </div>
                        </form>
                    </div>
                </main>
            </div>
        </div>
    </dialog>
{% endif %}

templates/parciais/_nav.html
{% load brfilters %}
<nav class="flex flex-col items-center px-20 w-full sticky top-0 bg-white bg-opacity-50 backdrop-blur-xl shadow-lg">
	<div class="flex items-center justify-between w-full border-b py-1 pb-1">
	<div class="flex justify-start flex-2 gap-10 items-center w-2/6">
		<div class="flex items-center text-sm font-normal">
			<button id="btn-menuModal"><img class="w-12 hover:bg-slate-100 p-1 rounded-full"
					src="../../media/produto_imagens/chart-svgrepo-com.svg" alt=""></button>
			<p>Menu</p>
		</div>

		<div>
			<ul class="flex items-center gap-5">

				<li><a class="hover:bg-slate-100 p-2 rounded-full" href="#">Assinaturas</a></li>
				<li><a class="hover:bg-slate-100 p-2 rounded-full" href="#">Categorias</a></li>

			</ul>
		</div>
	</div>

	<div class="flex items-center gap-10 justify-end w-1/3">
		{% if not request.user.is_authenticated %}
			<button class="flex items-center text-sm font-normal" id="btnConta">
				<p>Conta</p><img class="w-12 hover:bg-slate-100 p-1 rounded-full"
					src="../../media/produto_imagens/user-circle-svgrepo-com.svg" alt="">
			</button>

		{% else %}
			<button class="flex items-center text-sm font-normal" id="btnConta" type="button" data-dropdown-toggle="dropdown" onclick="toggleDropdown()">
				<p>{{ user }}</p>
				<img class="w-12 hover:bg-slate-100 p-1 rounded-full" src="../../media/produto_imagens/user-circle-svgrepo-com.svg" alt="">
			</button>
			
			<!-- Dropdown menu -->
			<div class="hidden bg-white text-base z-50 list-none divide-y divide-gray-100 rounded-2xl shadow-2xl my-4" id="dropdown">
				<div class="px-4 py-3">
					<span class="block text-lg font-semibold">{{ user }}</span>
					<span class="block text-sm font-medium text-gray-900 truncate">{{ user.email }}</span>
				</div>
				<ul class="py-1 flex flex-col" aria-labelledby="dropdown">
					<li>
						<a href="{% url 'perfil:atualizar' %}" class="flex items-center gap-4 text-sm hover:bg-gray-100 text-gray-700 px-4 py-2"><img class="w-5" src="../../media/produto_imagens/settings-svgrepo-com.svg" alt=""><span class="w-44 hover:pl-2 hover:transition-all duration-200">Minha conta</span></a>
					</li>
					<li>
						<a href="{% url 'pedido:lista' %}" class=" flex items-center gap-4 text-sm hover:bg-gray-100 text-gray-700 px-4 py-2"><img class="w-5" src="../../media/produto_imagens/cart-3-svgrepo-com.svg" alt=""><span class="w-44 hover:pl-2 hover:transition-all duration-200">Meus pedidos</span></a>
					</li>
					<li>
						<a href="#" class=" flex items-center gap-4 text-sm hover:bg-gray-100 text-gray-700 px-4 py-2"><img class="w-5" src="../../media/produto_imagens/folder-favourite-star-svgrepo-com.svg" alt=""><span class="w-44 hover:pl-2 hover:transition-all duration-200">Favoritos</span></a>
					</li>
					<li>
						<a href="{% url 'perfil:logout' %}" class=" flex items-center gap-4 text-sm hover:bg-gray-100 text-gray-700 px-4 py-2"><img class="w-5" src="../../media/produto_imagens/logout-2-svgrepo-com.svg" alt=""><span class="w-44 hover:pl-2 hover:transition-all duration-200">Sair</span></a>
					</li>
				</ul>
			</div>
		{% endif %}
	</div>
</div>
	<div class="flex items-center justify-center p-3	">
		<ul class="flex items-center gap-4">
			<li><a class="hover:bg-slate-100 p-4 rounded-full" href="#">Teste</a></li>
			<li><a class="hover:bg-slate-100 p-4 rounded-full" href="#">Teste</a></li>
			<li><a class="hover:bg-slate-100 p-4 rounded-full" href="#">Teste</a></li>
			<li><a class="hover:bg-slate-100 p-4 rounded-full" href="#">Teste</a></li>
			<li><a class="hover:bg-slate-100 p-4 rounded-full" href="#">Teste</a></li>
			<li><a class="hover:bg-slate-100 p-4 rounded-full" href="#">Teste</a></li>
			<li><a class="hover:bg-slate-100 p-4 rounded-full" href="#">Teste</a></li>
			<li><a class="hover:bg-slate-100 p-4 rounded-full" href="#">Teste</a></li>
			<li><a class="hover:bg-slate-100 p-4 rounded-full" href="#">Teste</a></li>
			<li><a class="hover:bg-slate-100 p-4 rounded-full" href="#">Teste</a></li>
			<li><a class="hover:bg-slate-100 p-4 rounded-full" href="#">Teste</a></li>
			<li><a class="hover:bg-slate-100 p-4 rounded-full" href="#">Teste</a></li>
		</ul>
	</div>
</nav>

templates/parciais/_pagination.html
{% if is_paginated %}
    <div class="col mt-3 mb-3">
        <div class="row">
            <div class="pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1">&laquo;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                        </li>
                    {% endif %}

                    {% for num in page_obj.paginator.page_range %}

                        {% if page_obj.number == num %}
                            <li class="page-item active">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endif %}

templates/parciais/_pedido.html
{% load static %}
{% load brfilters %}

<div class="row">
    <div class="col">
        <h3>{{ pedido }}</h3>
        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{ pedido.id }}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">{{ pedido.total|formata_preco }}</div>
            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4">{{ pedido.qtd_total }}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{ pedido.get_status_display }}</div>
        </div>
        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>
        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>

                {% for linha in pedido.itempedido_set.all %}
                <tr>
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}">
                    </td>
                    <td>{{ linha.produto }}</td>
                    <td>{{ linha.variacao }}</td>
                    <td>{{ linha.quantidade }}</td>
                    <td>
                        {% if linha.preco_promocional %}
                            {{ linha.preco_promocional|formata_preco }}
                        {% else %}
                            {{ linha.preco|formata_preco }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>